### ISSUE TITLE
Find out what are the additional information inside commit id

### ISSUE THREAD

**Issue by TobiasSekan** [Dark-Water/GitSubModulesVsPlugin#24]
v0.5-7-gf719c14
-> ID: f719c14...
-> Label: 0.5
-> Waht is: -7-g ???

heads/master-2-g9f98ea9
-> ID: 9f98ea9...
-> Label: heads/master
-> Waht is: -2-g ???

**Comment by Dark-Water** [comment]
see -> https://git-scm.com/docs/git-describe -> Examples

- The Number describe the additional commits since the commit of the Tag label
- The -g stands for Git
